# Generated by Django 6.1 on 2026-08-22 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0003_initial'),
        ('roadmaps', '0002_initial'),
        ('skill_tests', '0002_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roadmapnode',
            name='roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='roadmaps.roadmap'),
        ),
        migrations.AddField(
            model_name='roadmapnode',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_nodes', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='roadmapdependency',
            name='depends_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='roadmaps.roadmapnode'),
        ),
        migrations.AddField(
            model_name='roadmapdependency',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='roadmaps.roadmapnode'),
        ),
        migrations.AddField(
            model_name='roadmapnoderesource',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='roadmaps.roadmapnode'),
        ),
        migrations.AddField(
            model_name='roadmapnoderesource',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_usages', to='learning.learningresource'),
        ),
        migrations.AddField(
            model_name='roadmapnoderesource',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_usages', to='skill_tests.skilltest'),
        ),
        migrations.AddField(
            model_name='studentroadmapprogress',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='roadmaps.roadmapnode'),
        ),
        migrations.AddField(
            model_name='studentroadmapprogress',
            name='roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='roadmaps.roadmap'),
        ),
        migrations.AddField(
            model_name='studentroadmapprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=models.Index(fields=['student', 'status'], name='roadmaps_ro_student_e1a214_idx'),
        ),
        migrations.AddConstraint(
            model_name='roadmapdependency',
            constraint=models.CheckConstraint(condition=models.Q(('node', models.F('depends_on')), _negated=True), name='node_not_equal_depends_on'),
        ),
        migrations.AlterUniqueTogether(
            name='roadmapdependency',
            unique_together={('node', 'depends_on')},
        ),
        migrations.AddIndex(
            model_name='studentroadmapprogress',
            index=models.Index(fields=['student', 'roadmap'], name='roadmaps_st_student_1e0f88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentroadmapprogress',
            unique_together={('student', 'roadmap', 'node')},
        ),
    ]
