# Generated by Django 6.1 on 2026-08-22 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('test_type', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], db_index=True, default='EASY', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('total_questions', models.PositiveIntegerField(default=10)),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('time_limit_minutes', models.PositiveIntegerField(default=30)),
                ('pass_percentage', models.DecimalField(decimal_places=2, default=80, max_digits=5)),
                ('skill_points_reward', models.PositiveIntegerField(default=5)),
                ('xp_reward', models.PositiveIntegerField(default=30)),
                ('max_attempts', models.PositiveIntegerField(default=0)),
                ('cooldown_hours', models.PositiveIntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('passed', models.BooleanField(db_index=True, default=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score_percentage', models.DecimalField(decimal_places=2, default=80, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TRUE_FALSE', 'True/False'), ('MULTI_SELECT', 'Multiple Select'), ('CODE', 'Code')], default='MCQ', max_length=20)),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.CharField(max_length=500)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=20)),
                ('marks', models.PositiveIntegerField(default=10)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_scores', models.JSONField(default=dict)),
                ('passed', models.BooleanField(default=False)),
                ('skill_progression_applied', models.BooleanField(default=False)),
                ('skill_points_awarded', models.PositiveIntegerField(default=0)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('feedback', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
