# Generated by Django 6.1 on 2026-08-22 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skill_tests', '0002_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='skill_tests.skilltest'),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='skill_tests.testattempt'),
        ),
        migrations.AddField(
            model_name='testprerequisite',
            name='prerequisite_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_prerequisite_for', to='skill_tests.skilltest'),
        ),
        migrations.AddField(
            model_name='testprerequisite',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='skill_tests.skilltest'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.skill'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='skill_tests.skilltest'),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='skill_tests.testquestion'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='skill_tests.testattempt'),
        ),
        migrations.AddIndex(
            model_name='skilltest',
            index=models.Index(fields=['skill', 'test_type'], name='skill_tests_skill_i_fbe23e_idx'),
        ),
        migrations.AddIndex(
            model_name='skilltest',
            index=models.Index(fields=['test_type', 'is_active'], name='skill_tests_test_ty_3c3f20_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['student', 'test'], name='skill_tests_student_fc3c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['student', 'passed'], name='skill_tests_student_faa120_idx'),
        ),
        migrations.AddConstraint(
            model_name='testprerequisite',
            constraint=models.CheckConstraint(condition=models.Q(('test', models.F('prerequisite_test')), _negated=True), name='test_not_equal_prerequisite'),
        ),
        migrations.AlterUniqueTogether(
            name='testprerequisite',
            unique_together={('test', 'prerequisite_test')},
        ),
        migrations.AlterUniqueTogether(
            name='testanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
