# Generated by Django 6.1 on 2026-08-22 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='curriculumskillgap',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_gaps', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='curriculumskillgap',
            name='curriculum_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='institutions.curriculumversion'),
        ),
    ]
