# Generated by Django 6.1 on 2026-08-22 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curriculumversion',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_versions', to='institutions.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='institutions.department'),
        ),
        migrations.AddField(
            model_name='industrycurriculumalignment',
            name='curriculum_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_alignments', to='institutions.curriculumversion'),
        ),
        migrations.AddField(
            model_name='department',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='institutions.institution'),
        ),
        migrations.AlterUniqueTogether(
            name='courseskill',
            unique_together={('course', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='curriculumskillgap',
            unique_together={('curriculum_version', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='curriculumversion',
            unique_together={('department', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='industrycurriculumalignment',
            unique_together={('curriculum_version', 'industry_sector')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('institution', 'name')},
        ),
    ]
