# Generated by Django 6.1 on 2026-08-22 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('LEARNING', 'Learning'), ('STREAK', 'Streak'), ('ASSESSMENT', 'Assessment'), ('TEST', 'Test'), ('PROJECT', 'Project'), ('SOCIAL', 'Social'), ('CAREER', 'Career'), ('MILESTONE', 'Milestone')], default='MILESTONE', max_length=20)),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('criteria', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_secret', models.BooleanField(default=False)),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('UNCOMMON', 'Uncommon'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], default='COMMON', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('activity_type', models.CharField(choices=[('RESOURCE_COMPLETED', 'Resource Completed'), ('QUIZ_COMPLETED', 'Quiz Completed'), ('TEST_COMPLETED', 'Test Completed'), ('PROJECT_WORK', 'Project Work'), ('INTERVIEW_PRACTICE', 'Interview Practice'), ('ASSESSMENT_TAKEN', 'Assessment Taken'), ('LOGIN', 'Login'), ('PROFILE_UPDATE', 'Profile Update'), ('PLAN_COMPLETED', 'Plan Completed'), ('CODING_PRACTICE', 'Coding Practice')], db_index=True, max_length=30)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_meaningful', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], db_index=True, default='PLANNED', max_length=20)),
                ('total_targets', models.PositiveIntegerField(default=0)),
                ('completed_targets', models.PositiveIntegerField(default=0)),
                ('total_xp_available', models.PositiveIntegerField(default=0)),
                ('total_xp_earned', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('RESOURCE', 'Resource'), ('QUIZ', 'Quiz'), ('TEST', 'Test'), ('CODING_PRACTICE', 'Coding Practice'), ('PROJECT', 'Project'), ('INTERVIEW_PREP', 'Interview Prep'), ('REVISION', 'Revision'), ('CUSTOM', 'Custom')], db_index=True, default='RESOURCE', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('DEFERRED', 'Deferred')], db_index=True, default='PENDING', max_length=20)),
                ('xp_reward', models.PositiveIntegerField(default=20)),
                ('source', models.CharField(choices=[('AI_GENERATED', 'AI Generated'), ('MANUAL', 'Manual'), ('ROADMAP', 'Roadmap'), ('RECOMMENDATION', 'Recommendation')], default='MANUAL', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('total_active_days', models.PositiveIntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('streak_freezes_remaining', models.PositiveIntegerField(default=2)),
                ('streak_freezes_used', models.PositiveIntegerField(default=0)),
                ('streak_started_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('actual_duration_minutes', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('quality_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('xp_for_current_level', models.PositiveIntegerField(default=0)),
                ('xp_for_next_level', models.PositiveIntegerField(default=100)),
                ('title', models.CharField(default='Beginner', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Earned'), ('BONUS', 'Bonus'), ('STREAK_BONUS', 'Streak Bonus'), ('PENALTY', 'Penalty'), ('ADJUSTMENT', 'Adjustment'), ('ACHIEVEMENT', 'Achievement')], default='EARNED', max_length=20)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=500)),
                ('balance_after', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
