# Generated by Django 6.1 on 2026-08-22 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailytarget',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='planner.dailyplan'),
        ),
        migrations.AddField(
            model_name='streak',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='targetcompletion',
            name='target',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='planner.dailytarget'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earners', to='planner.achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlevel',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_level', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='xptransaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailyactivity',
            index=models.Index(fields=['student', 'date'], name='planner_dai_student_678cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyactivity',
            index=models.Index(fields=['student', 'activity_type'], name='planner_dai_student_ffa59e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyplan',
            unique_together={('student', 'date')},
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['current_streak'], name='planner_str_current_565e35_idx'),
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['last_active_date'], name='planner_str_last_ac_c17335_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('student', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='xptransaction',
            index=models.Index(fields=['student', 'transaction_type'], name='planner_xpt_student_f45d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='xptransaction',
            index=models.Index(fields=['student', 'created_at'], name='planner_xpt_student_8cdc5a_idx'),
        ),
    ]
