# Generated by Django 6.1 on 2026-08-22 21:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('avg_salary_range', models.CharField(blank=True, max_length=100)),
                ('growth_rate', models.CharField(blank=True, max_length=50)),
                ('demand_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], default='MEDIUM', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('PREREQUISITE', 'Prerequisite'), ('RELATED', 'Related'), ('COMPLEMENTARY', 'Complementary'), ('ADVANCED_VERSION', 'Advanced Version')], db_index=True, max_length=50)),
                ('strength', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proficiency_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('target_score', models.DecimalField(decimal_places=2, default=80, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('SELF_DECLARED', 'Self Declared'), ('DEVELOPING', 'Developing'), ('STRONG', 'Strong'), ('VERIFIED', 'Verified'), ('MASTERED', 'Mastered')], db_index=True, default='NOT_STARTED', max_length=50)),
                ('source', models.CharField(choices=[('SELF_DECLARED', 'Self Declared'), ('ASSESSMENT', 'Assessment'), ('TEST', 'Test'), ('PROJECT', 'Project'), ('CERTIFICATION', 'Certification'), ('INDUSTRY_FEEDBACK', 'Industry Feedback')], default='SELF_DECLARED', max_length=50)),
                ('last_assessed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=20)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('is_technical', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_skills', to='skills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='CareerRoleSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(choices=[('REQUIRED', 'Required'), ('PREFERRED', 'Preferred'), ('NICE_TO_HAVE', 'Nice to Have')], default='REQUIRED', max_length=20)),
                ('minimum_proficiency', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('career_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='skills.careerrole')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_roles', to='skills.skill')),
            ],
            options={
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='skills.skillcategory')),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='skills.skillcategory'),
        ),
        migrations.CreateModel(
            name='SkillEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_type', models.CharField(choices=[('ASSESSMENT', 'Assessment'), ('TEST', 'Test'), ('PROJECT', 'Project'), ('CERTIFICATION', 'Certification'), ('INTERNSHIP', 'Internship'), ('INDUSTRY_FEEDBACK', 'Industry Feedback'), ('INTERVIEW', 'Interview'), ('PRACTICAL_TASK', 'Practical Task')], db_index=True, max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('confidence', models.DecimalField(decimal_places=2, default=0.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('is_verified', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='skills.skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
