# Generated by Django 6.1 on 2026-08-22 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skillevidence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skillevidence',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skillrelationship',
            name='from_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='skillrelationship',
            name='to_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='studentskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_skills', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='studentskill',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='careerroleskill',
            unique_together={('career_role', 'skill')},
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category'], name='skills_skil_categor_292d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['parent_skill'], name='skills_skil_parent__158bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['difficulty_level'], name='skills_skil_difficu_ece5a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('name', 'category')},
        ),
        migrations.AddIndex(
            model_name='skillevidence',
            index=models.Index(fields=['student', 'skill'], name='skills_skil_student_18d499_idx'),
        ),
        migrations.AddIndex(
            model_name='skillevidence',
            index=models.Index(fields=['evidence_type'], name='skills_skil_evidenc_42de50_idx'),
        ),
        migrations.AddIndex(
            model_name='skillevidence',
            index=models.Index(fields=['student', 'evidence_type'], name='skills_skil_student_ba183b_idx'),
        ),
        migrations.AddConstraint(
            model_name='skillrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('from_skill', models.F('to_skill')), _negated=True), name='from_skill_not_equal_to_skill'),
        ),
        migrations.AlterUniqueTogether(
            name='skillrelationship',
            unique_together={('from_skill', 'to_skill', 'relationship_type')},
        ),
        migrations.AddIndex(
            model_name='studentskill',
            index=models.Index(fields=['student', 'status'], name='skills_stud_student_5b5fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentskill',
            index=models.Index(fields=['skill', 'proficiency_score'], name='skills_stud_skill_i_e94f51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentskill',
            unique_together={('student', 'skill')},
        ),
    ]
