# Generated by Django 6.1 on 2026-08-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('coding', 'Coding')], default='multiple_choice', max_length=20),
        ),
    ]
