# Generated by Django 6.1 on 2026-08-22 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceprerequisite',
            name='prerequisite_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.skill'),
        ),
        migrations.AddField(
            model_name='resourceprerequisite',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='learning.learningresource'),
        ),
        migrations.AddField(
            model_name='resourceprogress',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='learning.learningresource'),
        ),
    ]
