# Generated by Django 6.1 on 2026-08-22 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_initial'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='skill_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.skillcategory'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='resources',
            field=models.ManyToManyField(related_name='paths', to='learning.learningresource'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.learningpath'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learningresource'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
