# Generated by Django 6.1 on 2026-08-22 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0002_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceskill',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_taught', to='learning.learningresource'),
        ),
        migrations.AddField(
            model_name='resourceskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_resources', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='resourceverificationquiz',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_quizzes', to='learning.learningresource'),
        ),
        migrations.AddConstraint(
            model_name='resourceprerequisite',
            constraint=models.CheckConstraint(condition=models.Q(('prerequisite_resource__isnull', False), ('prerequisite_skill__isnull', False), _connector='OR'), name='prerequisite_resource_or_skill_required'),
        ),
        migrations.AddIndex(
            model_name='resourceprogress',
            index=models.Index(fields=['student', 'is_completed'], name='learning_re_student_0a8e68_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceprogress',
            index=models.Index(fields=['student', 'is_verified'], name='learning_re_student_275998_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourceprogress',
            unique_together={('student', 'resource')},
        ),
        migrations.AlterUniqueTogether(
            name='resourceskill',
            unique_together={('resource', 'skill')},
        ),
    ]
