# Generated by Django 6.1 on 2026-08-22 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewscore',
            name='interview',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_detail', to='interviews.mockinterview'),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.mockinterview'),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='interview',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='interviews.mockinterview'),
        ),
        migrations.AddIndex(
            model_name='mockinterview',
            index=models.Index(fields=['student', 'interview_type'], name='interviews__student_d3be60_idx'),
        ),
        migrations.AddIndex(
            model_name='mockinterview',
            index=models.Index(fields=['student', 'status'], name='interviews__student_ba0669_idx'),
        ),
    ]
