# Generated by Django 6.1 on 2026-08-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGuidanceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'User'), ('AI', 'AI'), ('SYSTEM', 'System')], default='USER', max_length=20)),
                ('content', models.TextField()),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerGuidanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_type', models.CharField(choices=[('CAREER_EXPLORATION', 'Career Exploration'), ('SKILL_GAP_ANALYSIS', 'Skill Gap Analysis'), ('LEARNING_ADVICE', 'Learning Advice'), ('INTERVIEW_PREP', 'Interview Prep'), ('RESUME_REVIEW', 'Resume Review'), ('GENERAL', 'General')], default='GENERAL', max_length=30)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('total_messages', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'User'), ('AI', 'AI'), ('SYSTEM', 'System')], default='USER', max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='New Chat', max_length=300)),
                ('context_type', models.CharField(choices=[('GENERAL', 'General'), ('SKILL_HELP', 'Skill Help'), ('ROADMAP', 'Roadmap'), ('DAILY_PLAN', 'Daily Plan'), ('TEST_PREP', 'Test Prep'), ('JOB_SEARCH', 'Job Search'), ('INTERVIEW', 'Interview'), ('LEARNING', 'Learning')], default='GENERAL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('total_messages', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
