# Generated by Django 6.1 on 2026-08-22 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guidance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careerguidancesession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidance_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='careerguidancemessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='guidance.careerguidancesession'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='guidance.chatsession'),
        ),
        migrations.AddIndex(
            model_name='careerguidancesession',
            index=models.Index(fields=['student', 'status'], name='guidance_ca_student_cf11d2_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['student', 'status'], name='guidance_ch_student_cd23cd_idx'),
        ),
    ]
