# Generated by Django 6.1 on 2026-08-22 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('jobs', '0002_initial'),
        ('skills', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationstatushistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='jobs.application'),
        ),
        migrations.AddField(
            model_name='applicationstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internshipposting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_postings', to='jobs.company'),
        ),
        migrations.AddField(
            model_name='internshipposting',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_internships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='jobs.company'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunityskill',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='opportunityskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_skills', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='studentjobmatch',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='studentjobmatch',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['student', 'status'], name='jobs_applic_student_09cda8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['content_type', 'object_id'], name='jobs_applic_content_6f8c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applied_at'], name='jobs_applic_applied_207476_idx'),
        ),
        migrations.AddIndex(
            model_name='internshipposting',
            index=models.Index(fields=['company', 'status'], name='jobs_intern_company_f31451_idx'),
        ),
        migrations.AddIndex(
            model_name='internshipposting',
            index=models.Index(fields=['deadline'], name='jobs_intern_deadlin_80654e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['company', 'status'], name='jobs_jobpos_company_68d43e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['job_type', 'experience_level'], name='jobs_jobpos_job_typ_926384_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['location', 'is_remote'], name='jobs_jobpos_locatio_524714_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['deadline'], name='jobs_jobpos_deadlin_2abcfa_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityskill',
            index=models.Index(fields=['content_type', 'object_id'], name='jobs_opport_content_0a4ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityskill',
            index=models.Index(fields=['skill'], name='jobs_opport_skill_i_f48998_idx'),
        ),
        migrations.AddIndex(
            model_name='studentjobmatch',
            index=models.Index(fields=['student', 'match_score'], name='jobs_studen_student_517d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentjobmatch',
            index=models.Index(fields=['content_type', 'object_id'], name='jobs_studen_content_e4ab05_idx'),
        ),
    ]
