/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 frontend/public/PrimaryIonDrive.glb --transform -o Building.jsx 
Files: frontend/public/PrimaryIonDrive.glb [5.8MB] > /home/YoomacKK/Documents/Hackathon-Project-Ai-Manthan-2.0-/PrimaryIonDrive-transformed.glb [247.54KB] (96%)
Author: indierocktopus (https://sketchfab.com/indierocktopus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/models/d3f50a66fee74c6588dd9bc92f7fe7b3
Title: Primary Ion Drive ///
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/PrimaryIonDrive-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="OSG_Scene">
        <group name="RootNode">
          <group name="circle">
            <mesh name="circle_constant1_0" geometry={nodes.circle_constant1_0.geometry} material={materials.constant1} />
            <mesh name="circle_HoloFillDark_0" geometry={nodes.circle_HoloFillDark_0.geometry} material={materials.HoloFillDark} />
          </group>
          <group name="geo1">
            <mesh name="geo1_constant1_0" geometry={nodes.geo1_constant1_0.geometry} material={materials.constant1} />
            <mesh name="geo1_HoloFillDark_0" geometry={nodes.geo1_HoloFillDark_0.geometry} material={materials.HoloFillDark} />
          </group>
          <group name="circle1">
            <mesh name="circle1_constant2_0" geometry={nodes.circle1_constant2_0.geometry} material={materials.constant2} />
          </group>
          <group name="circle2">
            <mesh name="circle2_constant2_0" geometry={nodes.circle2_constant2_0.geometry} material={materials.constant2} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/PrimaryIonDrive-transformed.glb')
