# Generated by Django 6.1 on 2026-08-22 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_role', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(default='My Resume', max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('completeness_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='ResumeGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('target_role', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('SUMMARY', 'Summary'), ('EDUCATION', 'Education'), ('EXPERIENCE', 'Experience'), ('SKILLS', 'Skills'), ('PROJECTS', 'Projects'), ('CERTIFICATIONS', 'Certifications'), ('ACHIEVEMENTS', 'Achievements'), ('VOLUNTEER', 'Volunteer'), ('LANGUAGES', 'Languages')], default='SUMMARY', max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('source_data_snapshot', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('template', models.CharField(default='professional', max_length=100)),
                ('content', models.JSONField(default=dict)),
                ('pdf_url', models.URLField(blank=True)),
                ('is_current', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
    ]
