# Generated by Django 6.1 on 2026-08-22 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industry', '0002_initial'),
        ('jobs', '0002_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='industryfeedback',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_provided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='industryfeedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='industryevaluation',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evaluations', to='industry.industryfeedback'),
        ),
        migrations.AddField(
            model_name='industrypartner',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='jobs.company'),
        ),
        migrations.AddField(
            model_name='industrypartner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='industry_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='industryproject',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='jobs.company'),
        ),
        migrations.AddField(
            model_name='industryproject',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='industryskilldemand',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_data', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='industryskillrequirement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='jobs.company'),
        ),
        migrations.AddField(
            model_name='industryskillrequirement',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_requirements', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='industry.industryproject'),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_project_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='industry.industryproject'),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectskill',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='industry.industryproject'),
        ),
        migrations.AddField(
            model_name='projectskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='industry.industryproject'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='industry.projectteam'),
        ),
        migrations.AddField(
            model_name='skilldemandsnapshot',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_snapshots', to='skills.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='industryevaluation',
            unique_together={('feedback', 'skill')},
        ),
        migrations.AddIndex(
            model_name='industryproject',
            index=models.Index(fields=['company', 'status'], name='industry_in_company_88e9b2_idx'),
        ),
        migrations.AddIndex(
            model_name='industryskilldemand',
            index=models.Index(fields=['skill', 'snapshot_date'], name='industry_in_skill_i_c4ff5d_idx'),
        ),
        migrations.AddIndex(
            model_name='industryskilldemand',
            index=models.Index(fields=['industry_sector'], name='industry_in_industr_99f335_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='industryskillrequirement',
            unique_together={('company', 'role_title', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='projectapplication',
            unique_together={('student', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='projectevaluation',
            unique_together={('project', 'student', 'evaluator')},
        ),
        migrations.AlterUniqueTogether(
            name='projectskill',
            unique_together={('project', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('team', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='skilldemandsnapshot',
            unique_together={('skill', 'period')},
        ),
    ]
