# Generated by Django 6.1 on 2026-08-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='career_goal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('INSTITUTION_ADMIN', 'Institution Admin'), ('INDUSTRY', 'Industry Professional'), ('MENTOR', 'Mentor'), ('SUPER_ADMIN', 'Super Admin')], default='STUDENT', max_length=20),
        ),
    ]
