# Generated by Django 6.1 on 2026-08-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ROLE_CHANGE', 'Role Change'), ('SKILL_VERIFY', 'Skill Verify'), ('ASSESSMENT_SUBMIT', 'Assessment Submit'), ('APPLICATION', 'Application'), ('ADMIN_ACTION', 'Admin Action')], max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('DAILY_TARGET', 'Daily Target'), ('STREAK', 'Streak'), ('TEST_UNLOCK', 'Test Unlock'), ('JOB', 'Job'), ('INTERNSHIP', 'Internship'), ('INTERVIEW', 'Interview'), ('ROADMAP', 'Roadmap'), ('ACHIEVEMENT', 'Achievement'), ('SYSTEM', 'System'), ('REMINDER', 'Reminder')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('DAILY_TARGET', 'Daily Target'), ('STREAK', 'Streak'), ('TEST_UNLOCK', 'Test Unlock'), ('JOB', 'Job'), ('INTERNSHIP', 'Internship'), ('INTERVIEW', 'Interview'), ('ROADMAP', 'Roadmap'), ('ACHIEVEMENT', 'Achievement'), ('SYSTEM', 'System'), ('REMINDER', 'Reminder')], max_length=30)),
                ('is_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
